// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwc0OqAE_Kfhs31epHYjNEjm0XP5q8mD4',
    appId: '1:795826839182:web:13f90f179b8e16aeb473df',
    messagingSenderId: '795826839182',
    projectId: 'ham-certificator',
    authDomain: 'ham-certificator.firebaseapp.com',
    storageBucket: 'ham-certificator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbAEcTMtdv-7Ianx-AT2vw_HLUi2lpFo',
    appId: '1:795826839182:android:069f2b855f676f50b473df',
    messagingSenderId: '795826839182',
    projectId: 'ham-certificator',
    storageBucket: 'ham-certificator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpO5aSVgnNg2kfWk_H3b4TSyIA_ogFcxE',
    appId: '1:795826839182:ios:b3a3414b7de9aabbb473df',
    messagingSenderId: '795826839182',
    projectId: 'ham-certificator',
    storageBucket: 'ham-certificator.appspot.com',
    iosBundleId: 'com.example.hamCertificator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpO5aSVgnNg2kfWk_H3b4TSyIA_ogFcxE',
    appId: '1:795826839182:ios:b3a3414b7de9aabbb473df',
    messagingSenderId: '795826839182',
    projectId: 'ham-certificator',
    storageBucket: 'ham-certificator.appspot.com',
    iosBundleId: 'com.example.hamCertificator',
  );
}
